use_frameworks!

platform :ios, '12.0'

target 'ImageDownloadManager_Example' do
  pod 'ImageDownloadManager', :path => '../'

  target 'ImageDownloadManager_Tests' do
    inherit! :search_paths

    
  end
end
